### ISSUE TITLE
Under `/home/doctors/{doctor_id}/comments/` , lost whether hide consult record field

### ISSUE THREAD

**Issue by powerformer** [mRcfps/rikang#17]
![image](https://user-images.githubusercontent.com/26423749/28237156-63856616-696b-11e7-8d23-c8ef5b430ae7.png)

**Comment by mRcfps** [comment]
We can add `service_type` and `order_no` field to comment model. If the patient chooses to share consult record, `order_no` field should be filled for server to fetch the record. And if not, set `order_no` field to null.
