### ISSUE TITLE
Some icon, add completed status, such as filled with `#F5F6F7`

### ISSUE THREAD

**Issue by powerformer** [mRcfps/rikang#19]
![image](https://user-images.githubusercontent.com/26423749/28239249-57d9e45c-699a-11e7-8ded-8f1c2c1dd881.png)
![image](https://user-images.githubusercontent.com/26423749/28239260-788e4698-699a-11e7-84db-de87ab9614e3.png)

**Comment by mRcfps** [comment]
I will give you a list of all icons later on in the newest sketch release.
