### ISSUE TITLE
Under `/users/patient/starred-questions/` should have `answer_num` filed, otherwise, will need one more http request

### ISSUE THREAD

**Issue by powerformer** [mRcfps/rikang#21]
![image](https://user-images.githubusercontent.com/26423749/28258091-fbb76078-6b01-11e7-87bf-eacef5778aa3.png)

**Comment by mRcfps** [comment]
[patient-starred-question](https://github.com/mRcfps/rikang/wiki/users:patient-starred-questions) and [patient-question](https://github.com/mRcfps/rikang/wiki/users:patient-starred-questions) all have the problem you stated. We'll fix it soon.
