### ISSUE TITLE
need Api  

### ISSUE THREAD

**Issue by powerformer** [mRcfps/rikang#9]
All fav posts
`/users/patients/{patient_id}/fav/posts/`

All fav doctor
`/users/patients/{patient_id}/fav/doctors/`

All questions that the patient has put
`/users/patients/{patient_id}/questions/`

All questions that the patient has star
`/users/patients/{patient_id}/starred/questions/`

All services that the patient has put
`/users/patients/{patient_id}/services/`

**Comment by mRcfps** [comment]
All finished.
